### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by ameerulislam** [Raynos/fake-cloudwatch-logs#5]
I cloned the repo then tried to npm install I get this error
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "fake-cloudwatch-logs" under a package
npm ERR! also called "fake-cloudwatch-logs". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

**Comment by Raynos** [comment]
You cannot install `fake-cloudwatch-logs` inside `fake-cloudwatch-logs`.

**Comment by ameerulislam** [comment]
I tried with different folder name and even different project name in jason
folder. Your project name and dependency name is the same. Fixing it
doesn't work either. Can you guide me ?

**Comment by ameerulislam** [comment]
Looks like renaming your package name in package.jason is working now.
